namespace LetsMeet.DA.Enums
{
    public enum Category
    {
        ArtsCulture,
        BookClubs,
        CareerBusiness,
        CarsMotorcycles,
        CommunityEnvironment,
        Dancing,
        EducationLearning,
        FashionBeauty,
        Fitness,
        FoodDrink,
        Games,
        HealthWellbeing,
        HobbiesCrafts,
        LanguageEthnicIdentity,
        Lifestyle,
        MovementsPolitics,
        MoviesFilm,
        Music,
        OutdoorsAdventure,
        ParentsFamily,
        PetsAnimals,
        Photography,
        ReligionBeliefs,
        SciFiFantasy,
        Singles,
        Socializing,
        SportsRecreation,
        Support,
        Tech,
        Writing
    }
}